insert into public.card_catalog (bank_name, card_name, network, default_benefits, default_annual_fee, card_color_theme)
values
('SBI Card', 'SBI Card ELITE', 'Mastercard', '[{"title":"Domestic Airport Lounge Access","category":"lounge","description":"2 complimentary domestic airport lounge visits per quarter (8 per year) via Visa/Mastercard lounge program. Not unlimited — quota is strictly 2 per quarter. 2 visits per quarter only — resets each calendar quarter. NOT unlimited. (2 visits/quarter)","value_estimate":null},{"title":"International Lounge via Priority Pass","category":"lounge","description":"6 complimentary international lounge visits per year via Priority Pass. Priority Pass membership must be activated through SBI Card portal before first use. Must activate Priority Pass on SBI Card portal before use. Only 6 complimentary visits per year — additional visits charged. (6 visits/year)","value_estimate":null},{"title":"2 Free Movie Tickets per Month","category":"shopping","description":"Buy 1 Get 1 free movie tickets on BookMyShow, up to 2 free tickets per month. Maximum discount ₹500 per ticket. Maximum ₹500 discount per ticket. Limited to 2 free tickets per calendar month. Subject to BookMyShow availability. (2 tickets/month)","value_estimate":null},{"title":"5X Reward Points on Dining, Grocery & Departmental","category":"shopping","description":"Earn 5X reward points on dining, grocery, and departmental store spends. 2X on all other retail spends. 1 reward point = ₹0.25. 1 reward point = ₹0.25. Points expire after 2 years. (5X pts (dining/grocery))","value_estimate":null},{"title":"Air Accident Insurance Cover","category":"other","description":"Personal accident death cover of ₹1 crore in case of air accidental death. Card must be active before incident. Verify exact activation conditions in card T&Cs. (₹1 crore cover)","value_estimate":null}]'::jsonb, 4999, 'slate'),
('SBI Card', 'SBI SimplyCLICK Credit Card', 'Visa', '[{"title":"10X Reward Points on Partner Merchants","category":"shopping","description":"10X reward points on Amazon, BookMyShow, Cleartrip, Lenskart, Netmeds, and other online partners. 5X on all other online spends. 1X on offline. 1 reward point = ₹0.25. Annual e-voucher worth ₹2,000 on ₹1L annual spend. (10X pts on partners)","value_estimate":null},{"title":"Annual e-Voucher on Milestone Spend","category":"shopping","description":"Earn e-voucher worth ₹2,000 on achieving ₹1,00,000 annual spend. Additional ₹2,000 voucher on ₹2,00,000 annual spend. Based on annual spend in card anniversary year, not calendar year. (₹2,000–4,000 voucher)","value_estimate":2000}]'::jsonb, 499, 'slate'),
('SBI Card', 'BPCL SBI Credit Card', 'Visa', '[{"title":"4.25% Value Back on BPCL Fuel","category":"fuel","description":"13X reward points on BPCL fuel purchases (4.25% effective value back including 1% surcharge waiver). Also 5X reward points on grocery, dining, movies, and departmental stores. Maximum 1,300 reward points per month on fuel spends. 1 reward point = ₹0.25. (4.25% on BPCL fuel)","value_estimate":null},{"title":"Fuel Surcharge Waiver at BPCL","category":"fuel","description":"1% fuel surcharge waiver on fuel transactions at BPCL pumps. Effectively increases total value back to 4.25%. Only at BPCL pumps. Other fuel stations not covered. (1% surcharge waiver)","value_estimate":null}]'::jsonb, 499, 'slate'),
('Axis Bank', 'Axis Magnus Credit Card', 'Visa', '[{"title":"Unlimited Domestic + International Lounge Access","category":"lounge","description":"Unlimited domestic airport lounge access for primary and add-on cardholders. IMPORTANT: Requires minimum spend of ₹50,000 in the previous 3 calendar months to qualify. This spend condition was introduced from 1 May 2024. Waived for first 3 months for new cardholders. Minimum ₹50,000 spend in previous 3 calendar months required. Effective 1 May 2024. Dreamfolks partnership ended July 2025 — now via Priority Pass for international, separate network for domestic. (Unlimited)","value_estimate":null},{"title":"12 EDGE Reward Points per ₹200 (up to ₹1.5L/month)","category":"shopping","description":"Earn 12 EDGE reward points per ₹200 on monthly spends up to ₹1.5 lakh. Earn 35 EDGE reward points per ₹200 on monthly spends exceeding ₹1.5 lakh. 5X points on Travel EDGE portal. 2 partner miles per 5 EDGE points across 20 travel partners. NO points on: Utility, Telecom, Rent (above ₹50K/month), Government, Wallet, Insurance, Gold/Jewellery, Fuel. Reward rate drops back to 12 pts/₹200 after exceeding credit limit + ₹1.5L in a month. No points on several excluded categories. (12 pts/₹200 (up to ₹1.5L/mo))","value_estimate":null},{"title":"Comprehensive Travel Insurance","category":"other","description":"Travel insurance cover including trip cancellation, lost baggage, and emergency medical cover up to ₹50 lakh for international travel. Verify exact cover terms in the card T&Cs. Travel must be booked using Axis Magnus card. (₹50 lakh travel cover)","value_estimate":null}]'::jsonb, 12500, 'emerald')
on conflict (bank_name, card_name) do update set
  network = excluded.network,
  default_benefits = excluded.default_benefits,
  default_annual_fee = excluded.default_annual_fee,
  card_color_theme = excluded.card_color_theme;