insert into public.card_catalog (bank_name, card_name, network, default_benefits, default_annual_fee, card_color_theme)
values
('Axis Bank', 'Axis Ace Credit Card', 'Visa', '[{"title":"5% Cashback on Swiggy, Zomato & Ola","category":"shopping","description":"5% cashback on Swiggy, Zomato, and Ola transactions. No monthly cap on this category. No cap on Swiggy/Zomato/Ola cashback. Annual fee waived on ₹2L spend. (5% back)","value_estimate":null},{"title":"4% Cashback on Bill Payments via Google Pay","category":"shopping","description":"4% cashback on utility bill payments, mobile recharges, and DTH payments made via Google Pay using Axis Ace card. Must pay via Google Pay specifically. Direct bank/biller payment not eligible. (4% back)","value_estimate":null},{"title":"2% Cashback on All Other Spends","category":"shopping","description":"2% cashback on all other spends not in the 5% or 4% category. No upper cap. Excludes fuel, wallet loads, and EMI transactions. (2% back (all others))","value_estimate":null},{"title":"Fuel Surcharge Waiver","category":"fuel","description":"1% fuel surcharge waiver at all fuel stations across India. Valid on transactions between ₹400 and ₹5,000. (1% waiver)","value_estimate":null}]'::jsonb, 499, 'emerald'),
('Axis Bank', 'Axis Flipkart Credit Card', 'Visa', '[{"title":"5% Cashback on Flipkart & Cleartrip, 7.5% on Myntra","category":"shopping","description":"5% cashback on Flipkart and Cleartrip purchases. 7.5% cashback on Myntra. 4% cashback on preferred partners: Swiggy, Uber, PVR INOX, cult.fit. 1% on all other spends. No upper cap on cashback amount. No lounge access as of June 2025. Cashback auto-adjusted in next statement. Excludes fuel, EMI, jewellery, insurance, government payments. (5–7.5% back)","value_estimate":null}]'::jsonb, 500, 'emerald'),
('ICICI Bank', 'Amazon Pay ICICI Credit Card', 'Visa', '[{"title":"5% Cashback on Amazon (Prime Members)","category":"shopping","description":"5% unlimited cashback on all Amazon.in purchases for Amazon Prime members. No monthly or annual cap. Requires active Amazon Prime membership. Non-Prime members get 3% cashback instead. (5% back (Prime))","value_estimate":null},{"title":"3% Cashback on Amazon (Non-Prime Members)","category":"shopping","description":"3% cashback on Amazon.in purchases for non-Prime members. Upgrade to Prime for 5% rate. Both rates have no upper cap. (3% back (non-Prime))","value_estimate":null},{"title":"2% Cashback on 200+ Partner Merchants","category":"shopping","description":"2% cashback at 200+ Amazon Pay partner merchants including Cleartrip, BigBasket, 1mg, and more. Partner list available on Amazon Pay portal. Check before assuming eligibility. (2% back (partners))","value_estimate":null},{"title":"1% Cashback on All Other Spends","category":"shopping","description":"1% cashback on all other spends not in the Amazon or partner categories. Excludes fuel and EMI transactions. (1% back)","value_estimate":null}]'::jsonb, 0, 'amber'),
('ICICI Bank', 'ICICI Coral Credit Card', 'Visa', '[{"title":"2 Free Movie Tickets per Month","category":"shopping","description":"Buy 1 Get 1 free on movie tickets via BookMyShow, up to 2 free tickets per month. Maximum discount ₹250 per ticket. Maximum ₹250 discount per ticket. 2 free tickets per calendar month. (2 tickets/month)","value_estimate":null},{"title":"Domestic Airport Lounge Access","category":"lounge","description":"1 complimentary domestic airport lounge visit per quarter via Visa/Mastercard lounge program. Verify current lounge access terms on ICICI portal — conditions may have changed. (1 visit/quarter)","value_estimate":null},{"title":"Fuel Surcharge Waiver","category":"fuel","description":"1% fuel surcharge waiver at all fuel stations. Check minimum/maximum transaction limits on ICICI portal. (1% waiver)","value_estimate":null}]'::jsonb, 500, 'amber')
on conflict (bank_name, card_name) do update set
  network = excluded.network,
  default_benefits = excluded.default_benefits,
  default_annual_fee = excluded.default_annual_fee,
  card_color_theme = excluded.card_color_theme;