insert into public.card_catalog (bank_name, card_name, network, default_benefits, default_annual_fee, card_color_theme)
values
('Kotak Mahindra Bank', 'Kotak Royale Signature Credit Card', 'Visa', '[{"title":"Domestic Airport Lounge Access","category":"lounge","description":"2 complimentary domestic airport lounge visits per quarter (8 per year). Verify current spend thresholds on Kotak portal — may require minimum quarterly spend. (2 visits/quarter)","value_estimate":null},{"title":"4X Reward Points on Travel, Entertainment & Dining","category":"shopping","description":"Earn 4X reward points on travel, entertainment, and dining spends. 2X on grocery. 1X on all other spends. Check point value and expiry on Kotak portal. (4X pts (travel/dining))","value_estimate":null},{"title":"Air Accident Insurance Cover","category":"other","description":"Personal accident death cover of ₹50 lakh in case of air accidental death. Card must be active before incident. Verify exact terms in card T&Cs. (₹50 lakh cover)","value_estimate":null},{"title":"Fuel Surcharge Waiver","category":"fuel","description":"1% fuel surcharge waiver at all fuel stations across India. Check transaction limits on Kotak portal. (1% waiver)","value_estimate":null}]'::jsonb, 999, 'midnight'),
('SBI Card', 'SBI Cashback Credit Card', 'Visa', '[{"title":"5% Cashback on All Online Spends","category":"shopping","description":"5% cashback on all online transactions across any website or app — not restricted to specific merchants. Capped at ₹5,000 cashback per statement cycle. No lounge access (was removed). Capped at ₹5,000 per statement cycle. Excludes insurance, fuel, EMI, government payments, jewellery. Lounge access was revoked — card no longer has this benefit. (5% back (cap ₹5,000/cycle))","value_estimate":5000},{"title":"1% Cashback on All Offline Spends","category":"shopping","description":"1% cashback on all offline/in-store purchases. Also capped at ₹5,000 combined with online cashback per statement cycle. Annual fee waived on ₹2L annual spend. (1% back (offline))","value_estimate":null}]'::jsonb, 999, 'slate'),
('HDFC Bank', 'HDFC Millennia Debit Card', 'Mastercard', '[{"title":"5% Cashback on Amazon, Flipkart & Swiggy","category":"shopping","description":"5% cashback on Amazon, Flipkart, Myntra, Swiggy, Zomato, BookMyShow, and other partner apps. Capped at ₹400 per month combined across all partner categories. Capped at ₹400/month total across all 5% partner categories. (5% back (cap ₹400/mo))","value_estimate":400},{"title":"Accidental Death Insurance Cover","category":"other","description":"Personal accidental death cover of up to ₹10 lakh for air, road, and rail accidents. Card must have been used at least once in preceding 30 days. Card must be active (used at least once in 30 days before incident). Verify exact activation condition in card T&Cs. (₹10 lakh accident cover)","value_estimate":null}]'::jsonb, 0, 'indigo'),
('SBI', 'SBI Gold Debit Card', 'Mastercard', '[{"title":"Personal Accident Insurance Cover","category":"other","description":"Personal accidental death cover of ₹2 lakh. Air accidental death cover of ₹4 lakh. Card must have been used for a purchase transaction in preceding 45–90 days for cover to be active. Card must have been used for a purchase (not ATM withdrawal) in 45–90 days before incident. Exact window varies — verify in card T&Cs. (₹2L (general) / ₹4L (air))","value_estimate":null},{"title":"Purchase Protection Cover","category":"other","description":"Covers items purchased with the card against fire and burglary for a limited period after purchase. Cover up to ₹5,000 per claim. Limited coverage window after purchase. Check exact duration in card T&Cs. (Up to ₹5,000)","value_estimate":null}]'::jsonb, 0, 'slate')
on conflict (bank_name, card_name) do update set
  network = excluded.network,
  default_benefits = excluded.default_benefits,
  default_annual_fee = excluded.default_annual_fee,
  card_color_theme = excluded.card_color_theme;