insert into public.card_catalog (bank_name, card_name, network, default_benefits, default_annual_fee, card_color_theme)
values
('IDFC FIRST Bank', 'IDFC FIRST Wealth Credit Card', 'Visa', '[{"title":"Domestic + International Lounge Access","category":"lounge","description":"1 complimentary domestic and international airport lounge visit per quarter. SPEND-GATED: requires ₹20,000 spend in current month to access lounge the following month. Must spend ₹20,000 in current calendar month to unlock lounge access for the next month. Spend threshold resets every month. (1 visit/quarter (spend-gated))","value_estimate":null},{"title":"1 Complimentary Golf Game per Month","category":"entertainment","description":"1 complimentary golf game or lesson per month at partner golf clubs. Requires ₹20,000 monthly spend to qualify. Requires ₹20,000 monthly spend to unlock. Subject to course availability. (1 game/month (spend-gated))","value_estimate":null},{"title":"2 Free Movie Tickets per Month","category":"shopping","description":"Buy 1 Get 1 free movie tickets via District app (by Zomato), up to 2 free tickets per month. Maximum ₹250 discount per ticket. Via District app (Zomato) only. Maximum ₹250 discount per ticket. 2 free tickets per calendar month. (2 tickets/month)","value_estimate":null},{"title":"Air Accident + Personal Accident Cover","category":"other","description":"Air accidental death cover of ₹1 crore. Personal accident cover of ₹10 lakh. Lost card liability cover of ₹50,000. Card must be active. Zero annual fee card — one of the best value insurance covers in its category. (₹1 crore air accident cover)","value_estimate":null},{"title":"10X Points on Dining, Travel & International Spends","category":"shopping","description":"Earn 10X reward points per ₹200 on dining, food delivery, travel, and international transactions. 3X on all other eligible spends above ₹2,000. 1X on insurance, utilities, railway, FASTag. Points never expire. 1 point = ₹0.25. No reward points on fuel, EMI, cash withdrawals. Points never expire — rare benefit. (10X pts (dining/travel))","value_estimate":null}]'::jsonb, 0, 'obsidian'),
('Yes Bank', 'YES First Preferred Credit Card', 'Mastercard', '[{"title":"Domestic Airport Lounge Access","category":"lounge","description":"2 complimentary domestic airport lounge visits per quarter (8 per year) via Mastercard lounge program. Verify current spend threshold requirements on Yes Bank portal. (2 visits/quarter)","value_estimate":null},{"title":"24 Reward Points per ₹200 on Travel & Dining","category":"shopping","description":"Earn 24 reward points per ₹200 on travel and dining spends. 12 reward points per ₹200 on all other spends. Check point value and expiry on Yes Bank portal. Annual fee waived on minimum annual spend — verify threshold. (24 pts/₹200 (travel/dining))","value_estimate":null},{"title":"Fuel Surcharge Waiver","category":"fuel","description":"1% fuel surcharge waiver at all fuel stations across India. Verify transaction limits on Yes Bank portal. (1% waiver)","value_estimate":null}]'::jsonb, 999, 'slate'),
('IndusInd Bank', 'IndusInd Legend Credit Card', 'Visa', '[{"title":"Unlimited Domestic Airport Lounge Access","category":"lounge","description":"Unlimited complimentary domestic airport lounge access. 2 complimentary international lounge visits per quarter via IndusInd Celesta program. Verify current lounge program terms on IndusInd portal — lounge partnerships change periodically. (Unlimited domestic)","value_estimate":null},{"title":"Complimentary Golf Access","category":"entertainment","description":"Complimentary golf games at premium golf courses across India. Verify exact quota and partner courses on IndusInd portal. (~₹3,000/game value)","value_estimate":3000}]'::jsonb, 9999, 'midnight'),
('RBL Bank', 'RBL Shoprite Credit Card', 'Mastercard', '[{"title":"20X Reward Points on Grocery (Saturdays)","category":"shopping","description":"Earn 20 reward points per ₹100 on grocery purchases made on Saturdays. 10 reward points per ₹100 on all other Saturday spends. 2 reward points per ₹100 on weekday spends. 20X rate only on Saturdays for grocery. All other days earn 2X. Check point value on RBL portal. (20X pts (grocery/Saturday))","value_estimate":null},{"title":"Domestic Airport Lounge Access","category":"lounge","description":"2 complimentary domestic airport lounge visits per quarter. Verify spend threshold (if any) on RBL portal before visiting lounge. (2 visits/quarter)","value_estimate":null},{"title":"Fuel Surcharge Waiver","category":"fuel","description":"1% fuel surcharge waiver at all fuel stations. Check transaction limits on RBL portal. (1% waiver)","value_estimate":null}]'::jsonb, 500, 'emerald')
on conflict (bank_name, card_name) do update set
  network = excluded.network,
  default_benefits = excluded.default_benefits,
  default_annual_fee = excluded.default_annual_fee,
  card_color_theme = excluded.card_color_theme;